// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "./components/header";
// import Footer from "./components/footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Monthly Expense",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="max-w-3xl mx-auto text-slate-800">
//           <div className="px-4">
//             <Header />
//           </div>
//           <main className="p-4 text-lg">{children}</main>
//           <div className="px-4">
//             <Footer />
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }

//! ===============

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "./components/header";
// import Footer from "./components/footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Monthly Expense",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="flex flex-col min-h-screen">
//           <Header />
//           <main className="flex-1 p-4 text-lg overflow-y-auto">
//             {children}
//           </main>
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Monthly Expense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}>
        <div style={{ flex: "1", display: "flex", flexDirection: "column" }}>
          <Header />
          <main style={{ flex: "1", overflowY: "auto", padding: "20px", background: "#f0f0f0" }}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
